extends Node
class_name _19_Unique_Statmod_Index


const EFFECT_UNIQUE_STATMOD = {
	"U_CHANGE_RAW_VALUE"       : U_CHANGE_RAW_VALUE,
	"U_EXCHANGE_TEXTURE"       : U_EXCHANGE_TEXTURE,

	"U_DEAL_PLAIN_DAMAGE"      : U_DEAL_PLAIN_DAMAGE,
	"U_DEAL_STRUCTURAL_DAMAGE" : U_DEAL_STRUCTURAL_DAMAGE,

	"U_SPAWN_TILE"             : U_SPAWN_TILE,
	"U_SPAWN_TILE_AROUND"      : U_SPAWN_TILE_AROUND,
	
	"U_MOVE_USER"            : U_MOVE_USER
}
