extends Node
class_name _Enum_MinimalComp


var ENUMS_TO_STRING = {
	"INTERACT"    : INTERACT,
	"TILE"        : TILE,
	"ACTOR"       : ACTOR,
	"LOOT_TABLE"  : LOOT_TABLE,
	"EFFECT_UNIT" : EFFECT_UNIT,
	"EFFECT_SLOT" : EFFECT_SLOT,
}



const TILE = [
	 C_7_TILE_STATIC_TILESET_NR
	,C_5_ANY_MATRIX_NOISE
	,C_0_ANY_DESCRIPTION
	,C_4_ANY_MAGIC_NOISE
	,C_1_ANY_IS_WALKABLE
	,C_2_ANY_TEXTURE_ID
	,C_3_ANY_LAYER
	,C_6_TILE_NAME
	]


const ACTOR = [
	 C_7_TILE_STATIC_TILESET_NR
	,C_26_ACTOR_INDIRECT_STATS
	,C_19_ACTOR_ATTRIBUTES
	,C_20_ACTOR_SKILLBLOCK
	,C_2_ANY_TEXTURE_ID
	,C_47_ANY_SYNONYM
	,C_6_TILE_NAME
	]


const INTERACT = [ 
	 C_7_TILE_STATIC_TILESET_NR
	,C_5_ANY_MATRIX_NOISE
	,C_4_ANY_MAGIC_NOISE
	,C_0_ANY_DESCRIPTION
	,C_2_ANY_TEXTURE_ID
	,C_3_ANY_LAYER
	,C_6_TILE_NAME
	]

const KITPART = [
	C_35_KIT_MECHANICAL_SUMMARY
	,C_33_KIT_COOLDOWN_TIMER
	,C_49_EFFECT_REFERENCE
	,C_38_KIT_PART_TYPE
	,C_31_KIT_CAT_TYPE
	,C_36_KIT_MOD_TIME
	,C_37_ANY_M_TYPE
	,C_37_ANY_M_TYPE
	,C_48_ANY_RARITY
	]


const LOOT_TABLE = [
	 C_7_TILE_STATIC_TILESET_NR
	,C_3_ANY_LAYER
	,C_6_TILE_NAME
	,C_2_ANY_TEXTURE_ID
	,C_0_ANY_DESCRIPTION
	,C_4_ANY_MAGIC_NOISE
	,C_5_ANY_MATRIX_NOISE
	,C_61_LOOT_TABLE
	,C_62_LOOT_STATE
	]


const EFFECT_SLOT = [
	 Effect_Unit_Component
	,Effect_Unit_Component
	,Effect_Unit_Component
	,Effect_Unit_Component
	]


const EFFECT_UNIT = [
	Effect_Comp_EFFECT_Condition
	,Effect_Comp_EFFECT_Statmod
	,Effect_Comp_TRIGGER_Base
	,Effect_Comp_TRIGGER_Specific
	,Effect_Comp_TIME
	,Effect_Comp_SPACE
	]




